### ISSUE TITLE
http://blazorbits.net broken in IE11

### ISSUE THREAD

**Issue by AdrienTorris** [BlazorBits/blazorbits.github.io#1]
Hello,

For information, the website http://blazorbits.net is not working.

Regards,

**Comment by davidnmbond** [comment]
Thanks @AdrienTorris,

The site does not work in Internet Explorer 11 at present...  Is that what you are using?

Thanks,

Daivd

**Comment by danielabbatt** [comment]
Tested and confirmed working on Windows 10 1803 (Build 17134.48) in
- Firefox 60.0.1 (64-bit)
- Chrome 66.0.3359.181 (Official Build) (64-bit)
- Edge 42.17134.1.0

Confirmed that IE 11 does not work.

**Comment by davidnmbond** [comment]
We need to move this issue to the other repo - opened there as https://github.com/BlazorBits/BlazorBits/issues/1

Closing the issue here.
